### ISSUE TITLE
E: Unknown Apple machine: MacBookPro12,1

### ISSUE THREAD

**Issue by abjugard** [bytbox/pommed-light#21]
Just got my new retina MacBook Pro (Early 2015) and would like to add support for my generation to pommed. Where do I start?

**Comment by bytbox** [comment]
Looking at past pull requests (almost all of which exist to add support to current machines) is the way to go. You'll need to use dmidecode and/or dmesg to get the ID numbers for your machine.

**Comment by abjugard** [comment]
Any chance you could make a new release so I can mark the package as outdated in [AUR](https://aur.archlinux.org/packages/pommed-light/)?

**Comment by bytbox** [comment]
I maintain the AUR package as well :P  I'll update both now. Thanks for the 
poke.

On Thu, 17 Sep 2015, Adrian Bjugård wrote:

> Any chance you could make a new release so I can mark the package as outdated in [AUR](https://aur.archlinux.org/packages/pommed-light/)?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bytbox/pommed-light/issues/21#issuecomment-141238600

-- 
Scott Lawrence

**Comment by IvanMalison** [comment]
@bytbox Can you update AUR.

**Comment by bytbox** [comment]
No, I just forgot about that version number. The AUR copy is up-to-date.
