### ISSUE TITLE
Unknown Apple machine: MacBookPro11,5

### ISSUE THREAD

**Issue by knope** [bytbox/pommed-light#25]
/usr/bin/pommed -d
I: pommed v1.45lw Apple laptops hotkeys handler
I: Copyright (C) 2006-2011 Julien BLACHE jb@jblache.org
pommed configuration:
- General settings:
  fnmode: 1
- sysfs backlight control:
  initial level: -1
  step: 1
  on_batt: 6
- ATI X1600 backlight control:
  initial level: -1
  step: 10
  on_batt: 80
- Intel GMA950 backlight control:
  initial level: 0xffffffff
  step: 0xf
  on_batt: 0x40
- nVidia GeForce 8600M GT backlight control:
  initial level: -1
  step: 1
  on_batt: 6
- Audio volume control:
  card: default
  initial volume: -1
  step: 10%
  beep: yes
  volume element: PCM
  speaker element: Front
  headphones element: Headphone
- Keyboard backlight control:
  default level: 100
  step: 10
  auto on threshold: 20
  auto off threshold: 40
  auto enable: yes
  idle timer: 60s
  idle level: 0
- CD eject:
  enabled: yes
  device: /dev/dvd
- Beep:
  enabled: no
  beepfile: /usr/share/pommed/goutte.wav
- Apple Remote IR Receiver:
  enabled: no
  DMI vendor name: [Apple Inc.]
  DMI product name: [MacBookPro11,5]
  E: Unknown Apple machine: MacBookPro11,5
  E: Unknown Apple machine

**Comment by fradeve** [comment]
same here

**Comment by Ram-Z** [comment]
See #28

**Comment by knope** [comment]
wooo
