### ISSUE TITLE
LCD backlight probe fails on boot but not on restart

### ISSUE THREAD

**Issue by arthurwhite** [bytbox/pommed-light#32]
I enabled the *pommed.service* but it fails (only) after boot:
```
E: sysfs backlight probe failed, no fallback for this machine
E: LCD backlight probe failed, check debug output
```
But if I `systelctl restart pommed`, pommed starts and runs good.

Otherwise, when [nvidia-bl](https://aur.archlinux.org/packages/nvidia-bl/) is installed (with apple_bl kernel module disabled), pommed does **not** crash after boot **but** the screen backlight Fx keys (and only them) have no effect.

![fullsizeoutput_61a](https://cloud.githubusercontent.com/assets/9503891/21778934/aeb7c4de-d6a5-11e6-9332-40797eb2709e.jpeg)

PS : Et merci pour le travail fourni jusqu'ici ! 👍

**Comment by bytbox** [comment]
Which version of macbook do you have? It sounds like pommed is starting before apple_bl is done initializing, right?

(This sounds eerily familiar, like there's already a similar bug report.)

**Comment by bytbox** [comment]
Ah, this is superficially similar to #24. Not sure the same hack will work though.

**Comment by arthurwhite** [comment]
Yes, I think I also have a race condition.
With which unit(s)? I don't know. I have 5 different active units having "backlight" in their name.
What I know is that pommed has been successfully launched by systemd once in ~10 reboots, without any correlative config change. 

Now, it's weird that I can't manage to defer the launch of pommed.
I edited the service file with
```
[Unit]
After=multi-user.target
```
or even a dirty
```
[Timer]
OnBootSec=60
```
and pommed still failed several seconds **before** the user login (and I went fast…).

#### My setup
* MacBookPro7,1
* kernel 4.8.13-1-ARCH
* pommed 1.45lw

**Comment by arthurwhite** [comment]
It works!®

I reinstalled [nvidia-bl](https://aur.archlinux.org/packages/nvidia-bl/) but this time, I uncommented the "options" line in `/etc/modprobe.d/nvidia_bl.conf`.
Disabling apple_bl kernel module was not necessary.

For the record, I also replaced *nouveau* with the proprietary Nvidia drivers (but I don't think it's related as *pommed.service* still failed after this).
