### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by ericfreese** [bytbox/pommed-light#35]
Looks like it's been just about 2 years since the [last release](https://github.com/bytbox/pommed-light/releases/tag/v1.50lw). Are there plans to cut a new release soon? Would be nice to see #26 and #28 released.

**Comment by bytbox** [comment]
Why can't you just let me be lazy in peace? :P 

I've updated the version and tagged a new release. Let me know if I forgot any important steps.

I'll mention it here (and on every issue filed from now on): this project is up for adoption! I haven't used or owned a mac in 5 years.
